on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.0"
          channel: stable

      - name: Create Keystore Properties
        run: |
          echo "storeFile=upload-keystore.jks" > android/key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

      - name: Set up Java environment
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'


      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Build APK & App Bundle
        run: |
          flutter build apk --release
          flutter build appbundle --release

      - name: Create Git Tag
        id: tag
        run: |
          TAG_NAME=v1.0.${{ github.run_number }}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Upload Release to GitHub
        uses: ncipollo/release-action@v1
        with:
          name: "Release v1.0.${{ github.run_number }}"
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          tag: ${{ env.TAG_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK & AAB as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-aab
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab

      - name: Decode Play Store JSON Key
        run: echo '${{ secrets.PLAY_STORE_JSON }}' | base64 --decode > play-store-key.json

      - name: Deploy to Play Store (Internal Testing)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_JSON }}
          packageName: com.bscs3a.navbook
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
          status: draft